# Docker Compose configuration for GPAF
services:
  gpaf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpaf_agent
    ports:
      - "50001:5000"  # Web UI port
      - "55022:22"    # SSH port
    volumes:
      # Application data persistence
      - ./memory:/app/memory
      - ./knowledge:/app/knowledge  
      - ./logs:/app/logs
      - ./work_dir:/app/work_dir
      - ./tmp:/app/tmp
      # Mount project source for development (optional)
      - .:/app/src
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - WEB_UI_HOST=0.0.0.0
      - WEB_UI_PORT=5000
      - DISABLE_RFC=true
      
      # Authentication (change these for security)
      - AUTH_LOGIN=admin
      - AUTH_PASSWORD=gpaf123
      
      # API Keys (set these in your environment or .env file)
      - API_KEY_OPENAI=${API_KEY_OPENAI:-}
      - API_KEY_ANTHROPIC=${API_KEY_ANTHROPIC:-}
      - API_KEY_GOOGLE=${API_KEY_GOOGLE:-}
      - API_KEY_MISTRAL=${API_KEY_MISTRAL:-}
      - API_KEY_GROQ=${API_KEY_GROQ:-}
      - API_KEY_PERPLEXITY=${API_KEY_PERPLEXITY:-}
      
      # Database and storage
      - SQLITE_DB_PATH=/app/memory/database.db
      - LOG_LEVEL=INFO
      
      # Tiktoken cache
      - TIKTOKEN_CACHE_DIR=/tmp/tiktoken_cache
      
    restart: unless-stopped
    networks:
      - gpaf_network

networks:
  gpaf_network:
    driver: bridge